"""
Pydantic data models for the Murder Mystery game.

Defines the structured schema for all mystery components
generated by Gemini AI.
"""

from pydantic import BaseModel, Field, field_validator
from typing import Optional


class Suspect(BaseModel):
    """Represents a suspect in the murder mystery."""

    id: str = Field(..., description="Unique identifier, e.g. 'suspect_1'")
    name: str = Field(..., description="Full name of the suspect")
    occupation: str = Field(..., description="Job title or role")
    relationship: str = Field(..., description="Relationship to the victim")
    motive: str = Field(..., description="Why they might have committed the crime")
    alibi: str = Field(..., description="Their claimed whereabouts at time of crime")
    is_murderer: bool = Field(
        default=False,
        description="True only for the guilty party"
    )


class Clue(BaseModel):
    """Represents a piece of evidence in the investigation."""

    id: str = Field(..., description="Unique identifier, e.g. 'clue_1'")
    title: str = Field(..., description="Short label for the clue")
    description: str = Field(..., description="Detailed narrative description")
    type: str = Field(
        ...,
        description="Category: fingerprint, witness, footage, document, physical, digital"
    )
    related_suspect_id: Optional[str] = Field(
        default=None,
        description="Links clue to a suspect if applicable"
    )

    @field_validator("type")
    @classmethod
    def validate_clue_type(cls, v: str) -> str:
        allowed = {
            "fingerprint", "witness", "footage", "document",
            "physical", "digital", "testimonial", "forensic",
            "receipt", "phone_record", "other"
        }
        # Be lenient — normalise and accept if close enough
        normalised = v.lower().strip().replace(" ", "_")
        if normalised not in allowed:
            return "other"
        return normalised


class Contradiction(BaseModel):
    """Represents a hidden contradiction between alibis, clues, or statements."""

    id: str = Field(..., description="Unique identifier")
    description: str = Field(..., description="What the contradiction is")
    clue_ids: list[str] = Field(
        ...,
        description="Which clues are involved in this contradiction"
    )
    suspect_id: str = Field(
        ...,
        description="Which suspect's story is undermined"
    )
    hint: str = Field(
        ...,
        description="A subtle hint to help the player find it"
    )


class Mystery(BaseModel):
    """
    Complete murder mystery case generated by Gemini AI.
    This is the top-level model validated against the AI response.
    """

    victim_name: str = Field(..., description="Name of the victim")
    victim_occupation: str = Field(..., description="Victim's profession")
    victim_backstory: str = Field(..., description="2-3 sentence backstory")
    crime_scene: str = Field(..., description="Location name")
    crime_scene_description: str = Field(
        ...,
        description="Atmospheric description of the scene"
    )
    time_of_death: str = Field(..., description="Approximate time of death")
    cause_of_death: str = Field(..., description="How the victim died")
    initial_report: str = Field(
        ...,
        description="Opening narrative the detective reads"
    )
    suspects: list[Suspect] = Field(
        ...,
        description="Exactly 3 suspects"
    )
    clues: list[Clue] = Field(
        ...,
        description="5-8 investigation clues"
    )
    contradictions: list[Contradiction] = Field(
        ...,
        description="2-4 hidden contradictions"
    )
    murderer_id: str = Field(
        ...,
        description="ID of the guilty suspect"
    )
    solution_narrative: str = Field(
        ...,
        description="Full explanation of how and why the murder happened"
    )

    @field_validator("suspects")
    @classmethod
    def validate_suspect_count(cls, v: list[Suspect]) -> list[Suspect]:
        if len(v) < 2:
            raise ValueError(f"Need at least 2 suspects, got {len(v)}")
        if len(v) > 6:
            raise ValueError(f"Too many suspects ({len(v)}), max is 6")
        return v

    @field_validator("clues")
    @classmethod
    def validate_clue_count(cls, v: list[Clue]) -> list[Clue]:
        if len(v) < 1:
            raise ValueError("Must have at least 1 clue")
        return v

    @field_validator("contradictions")
    @classmethod
    def validate_contradiction_count(cls, v: list[Contradiction]) -> list[Contradiction]:
        if len(v) < 1:
            raise ValueError("Must have at least 1 contradiction")
        return v
